### ISSUE TITLE
Telegraf fields using the same name

### ISSUE THREAD

**Issue by ajohnson-512** [influxdata/docs.influxdata.com#2258]
###### What products and version are you using?
Telegraf 1.1

###### Where did you look before opening the issue?
https://docs.influxdata.com/telegraf/v1.10/administration/configuration/
https://raw.githubusercontent.com/influxdata/telegraf/master/etc/telegraf.conf

Two processors contain field names that are identical:
inputs.disk and inputs.mem both contain "free" "total" and "used" field names.  Is there a way to rename/prefix/suffix these fields to make them unique? I've been unable to find documentation on these and I need a way to be able to rename both sets of data - using the processors.rename.replace will take the first instance it finds and rename all data eg

  [[processors.rename.replace]]
    field = "used"
    dest = "mem_used"

will rename any collectors with from used to mem_used.

tia

**Comment by sanderson** [comment]
@ajohnson-512 is there a reason you need them to be unique? Though the field names are the same, they are stored in separate measurements. The measurement acts as a namespace when querying data.

**Comment by ajohnson-512** [comment]
Hello -

I'm very new to Telegraf, so this could very well be a misunderstanding on my part, or maybe I could have explained better.

We're staging Telegraf as a replacement poller, feeding Influx.  We already have set field names in the db, and I need to match those so we can continue to feed the data in.

I'm using processors.rename.replace to rename the fields to what I need, however, I've run into the problem of attempting to rename the fields with that contain the same exact names.  inputs.disk and inputs.mem both have 'free' 'total' and 'used'.  

Using the rename processor:

[[processors.rename.replace]]
field = "used"
dest = "mem_used"

will take all fields named 'used' and rename them to 'mem_used' - resulting in the disk used measurement to be renamed 'mem_free', when I do not want that to happen.  Is there a way I can limit that rename to JUST apply to the inputs.mem collector?

**Comment by sanderson** [comment]
Well I learned something new in talking to the Telegraf engineers. You can actually nest processors under inputs. So the following configuration would do what you're looking for:

```toml
[[inputs.mem]]
  [[processors.rename.replace]]
    field = "used"
    dest = "mem_used"

[[inputs.disk]]
  [[processors.rename.replace]]
    field = "used"
    dest = "disk_used"
```

**Comment by ajohnson-512** [comment]
Hello,

I attempted to place the rename processor within the input definition, but received an error:

telegraf --config /etc/telegraf/myconf.conf
2019-05-29T01:11:38Z I! Starting Telegraf 1.10.4
2019-05-29T01:11:38Z E! [telegraf] Error running agent: Unsupported config format: rename, file /etc/telegraf/myconf.conf

Here's the input I had defined:

[[inputs.mem]]
  [[processors.rename.replace]]
    field = "used"
    dest = "mem_used"
  fielddrop = ["available", "available_percent", "commit_limit", "committed_as", "dirty", "high_free", "high_total", "huge_page_size", "huge_pages_free", "huge_pages_total", "inactive", "low_free", "low_total", "mapped", "page_tables", "slab", "swap_cached", "swap_free", "swap_total", "used_percent", "vmalloc_chunk", "vmalloc_total", "vmalloc_used", "wired", "write_back", "write_back_tmp"]

I tried using the processor at the beginning, as above, and at the end of the definition, with the same effect. Thoughts?

**Comment by sanderson** [comment]
@glinton ^^

**Comment by glinton** [comment]
Try:
```toml
[[inputs.mem]]
  fielddrop = ["available", "available_percent", "commit_limit", "committed_as", "dirty", "high_free", "high_total", "huge_page_size", "huge_pages_free", "huge_pages_total", "inactive", "low_free", "low_total", "mapped", "page_tables", "slab", "swap_cached", "swap_free", "swap_total", "used_percent", "vmalloc_chunk", "vmalloc_total", "vmalloc_used", "wired", "write_back", "write_back_tmp"]
  [[processors.rename]]
    [[processors.rename.replace]]
      field = "used"
      dest = "mem_used"
```

**Comment by glinton** [comment]
My apologies, I was mistaken in thinking that processors can be applied to individual inputs. It's now an unofficial feature request :wink:

According to [the documentation](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering): 

>Metric filtering can be configured per plugin on any input, output, processor, and aggregator plugin.

In order to filter which measurement get's applied to which processor, you'll need to specify a metric filter:

```toml
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
  fielddrop = ["inodes_free", "inodes_total", "inodes_used"]

[[inputs.mem]]
  fielddrop = ["available", "available_percent", "commit_limit", "committed_as", "dirty", "high_free", "high_total", "huge_page_size", "huge_pages_free", "huge_pages_total", "inactive", "low_free", "low_total", "mapped", "page_tables", "slab", "swap_cached", "swap_free", "swap_total", "used_percent", "vmalloc_chunk", "vmalloc_total", "vmalloc_used", "wired", "write_back", "write_back_tmp"]

[[processors.rename]]
  namepass=["mem"]
  [[processors.rename.replace]]
    field = "used"
    dest = "mem_used"

[[processors.rename]]
  namepass=["disk"]
  [[processors.rename.replace]]
    field = "used"
    dest = "disk_used"
```

Notice the `namepass` specifying the name of the metric that processor should apply to.
