### ISSUE TITLE
Update Enterprise HTTPS docs to include cluster config

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2562]
The current InfluxDB Enterprise HTTPS setup doc doesn't mention configuring certificates in the `[cluster]` section of the data node configuration file. Certificates need to be configured in both the `[http]` and `[cluster]` sections. The `[http]` section configures the API endpoint of the InfluxDB instance. The `[cluster]` section defines how data nodes within a cluster interact with each other.

```toml
# ...

[http]

  # ...

  # Determines whether HTTPS is enabled.
  https-enabled = true

  # The SSL certificate to use when HTTPS is enabled.  The certificate should be a PEM encoded
  # bundle of the certificate and key.  If it is just the certificate, a key must be
  # specified in https-private-key.
  https-certificate = "/etc/ssl/influxdb.pem"

  # Use a separate private key location.
  # https-private-key = ""

# ...

[cluster]

  # ...

  # Determines whether data nodes use HTTPS to communicate with each other.
  https-enabled = true

  # The SSL certificate to use when HTTPS is enabled.  The certificate should be a PEM encoded
  # bundle of the certificate and key.  If it is just the certificate, a key must be
  # specified in https-private-key.
  https-certificate = "/etc/ssl/influxdb.pem"

  # Use a separate private key location.
  # https-private-key = ""

# ...
  ```

###### URL for relevant page?
- https://docs.influxdata.com/enterprise_influxdb/v1.7/guides/https_setup/
