### ISSUE TITLE
How to convert strings into numeric values

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs.influxdata.com#2648]
_Suggested as a Tech Tip somewhere in the docs (maybe processors plugin page)??_ 

A common issue people run into is not realizing they are aren't seeing the data in the UI because their numeric values are reporting as strings.  Users don't realize a number in quotes indicates string. 

Example input where numeric values are reported as strings:
```json
{
"minutes": "2",
"platform": "2",
"direction": "North",
"length": "10",
"color": "YELLOW",
"hexcolor": "#ffff33",
"bikeflag": "1",
"delay": "66"
}
```

Configuration requires 1) configuring field as string AND 2) using the converter processor.  If users realize they have numbers reporting as strings, they will often forget the first part. 
```toml
[[inputs.http]]
## HTTP configs
json_string_fields = ["minutes"]

[[processors.converter]]
   [processors.converter.fields]
      integer = ["minutes"]
```

###### What products and version are you using?
1.x & 2.0

###### Where did you look before opening the issue?
Converter Processor GitHub README
